GET http://localhost:5000/

###
POST http://localhost:5000/customer/register
Content-Type: application/json

{
    "name": "Ashikuzzaman Abir",
    "email": "asrabirphone1@gmail.com",
    "password": "11223344",
    "dateOfBirth": "1999-5-4"
}

###

GET http://localhost:5000/customer

###
DELETE http://localhost:5000/customer/66350262fb935cd626c9dfcb